#!/usr/bin/env python3
"""生成 Shottr 中文翻译词典 plist（写入应用 Resources）"""
import plistlib

EXACT = {
    # ===== 状态栏菜单 =====
    'Area Capture': '区域截图',
    'Window Capture': '窗口截图',
    'Capture Active Window': '截取活动窗口',
    'Capture Any Window': '截取任意窗口',
    'Fullscreen Screenshot': '全屏截图',
    'Delayed Screenshot (3s)': '延时截图（3秒）',
    'Scrolling Capture': '滚动截图',
    'Scrolling Capture (Up)': '滚动截图（向上）',
    'Manual Scrolling Capture': '手动滚动截图',
    'Repeat Area Capture': '重复上次区域截图',
    'Load From Clipboard': '从剪贴板载入',
    'Paste Image': '粘贴图像',
    'Open File': '打开文件',
    'Open Image': '打开图像',
    'Open': '打开',
    'Show Shottr': '显示 Shottr',
    'Settings': '设置',
    'Preferences…': '偏好设置…',
    'Preferences': '偏好设置',
    'Library': '截图库',
    'Screenshot Library': '截图库',
    'Recognize Text/QR': '识别文字/二维码',
    'Text/QR Recognition': '文字/二维码识别',
    'Quit': '退出',
    'Quit Shottr': '退出 Shottr',
    'Capture': '截图',
    'Add Capture': '新建截图',
    'CHECK NEW VERSION': '检查新版本',
    'Manage Uploads': '管理上传',
    'Show Recent Captures': '显示最近截图',
    'Start Scrolling (Up or Down)': '开始滚动（向上或向下）',
    'Stop': '停止',
    'Close': '关闭',
    'Cancel': '取消',
    'Accept': '接受',
    'Change': '更改',
    'Clear': '清除',
    'Save': '保存',
    'Save As': '另存为',
    'Save Image': '保存图像',
    'Save Image As': '图像另存为…',
    'Copy': '拷贝',
    'Copy Image': '拷贝图像',
    'Cut': '剪切',
    'Paste': '粘贴',
    'Delete': '删除',
    'Upload': '上传',
    'Upload Image': '上传图像',
    'Print': '打印',
    'Pin to Screen': '钉在屏幕上',
    'Pin': '钉住',
    'Erase': '擦除',

    # ===== 编辑器工具（带快捷键提示）=====
    'Draw': '绘图',
    'Arrow': '箭头',
    'Text': '文字',
    'Rectangle': '矩形',
    'Oval': '椭圆',
    'Line': '直线',
    'Freehand Drawing': '自由绘制',
    'Magnifier': '放大镜',
    'Highlighter': '荧光笔',
    'Blur': '模糊',
    'Spotlight': '聚光灯',
    'Counter': '编号',
    'Ruler': '标尺',
    'Backdrop': '背景',
    'Crop': '裁剪',
    'Marker': '标记',
    'Number': '编号',
    'Arrow (A)': '箭头 (A)',
    'Backdrop (K)': '背景 (K)',
    'Blur/Erase (B)': '模糊/擦除 (B)',
    'Blur/Erase': '模糊/擦除',
    'Counter (C)': '编号 (C)',
    'Freehand Drawing (D)': '自由绘制 (D)',
    'Highlighter (H)': '荧光笔 (H)',
    'Line (L)': '直线 (L)',
    'Magnifier (M)': '放大镜 (M)',
    'Oval (O)': '椭圆 (O)',
    'Rectangle (R)': '矩形 (R)',
    'Spotlight (S)': '聚光灯 (S)',
    'Text (T)': '文字 (T)',
    'Ruler (1 or 2)': '标尺 (1 或 2)',

    # ===== 偏好设置 =====
    'Launch at Startup': '开机时启动',
    'Choose default folder': '选择默认文件夹',
    'Pick a folder for your screenshots.': '为你的截图选择一个文件夹。',
    'Transparent Background': '透明背景',
    'Add Gradient Background': '添加渐变背景',
    'Enable URL Scheme (Deep Links)': '启用 URL Scheme（深层链接）',
    'Enable Image Upload in app settings first': '请先在应用设置中启用图像上传',
    'Checking connection': '正在检查连接',
    'Reset all settings': '重置所有设置',
    'General': '通用',
    'Advanced': '高级',
    'Hotkey': '快捷键',
    'License': '许可证',
    'Shortcuts': '快捷键',
    'Shortcut': '快捷键',
    'Shortcut 1': '快捷键 1',
    'Shortcut 2': '快捷键 2',
    'Files': '文件',
    'Folder': '文件夹',
    'Cloud': '云端',
    'Custom': '自定义',
    'Default': '默认',
    'Auto': '自动',
    'On': '开启',
    'Off': '关闭',
    'Yes': '是',
    'No': '否',
    'OK': '好',
    'Width': '宽度',
    'Height': '高度',
    'Size': '大小',
    'Color': '颜色',
    'Colors': '颜色',
    'Opacity': '不透明度',
    'Thickness': '粗细',
    'Font': '字体',
    'Language': '语言',
    'Version': '版本',
    'Name': '名称',
    'Image': '图像',
    'Search': '搜索',
    'Dark': '深色',
    'Light': '浅色',
    'PNG': 'PNG',
    'JPEG': 'JPEG',
    'Token': '令牌',
    'Uploads': '上传',
    'Region': '区域',

    # ===== 提示与通知 =====
    'Shottr needs permission to record the screen': 'Shottr 需要屏幕录制权限',
    'Permissions Not Granted': '未获得权限',
    'No Image to Upload': '没有可上传的图像',
    'Image Upload is Off': '图像上传已关闭',
    'Upload Succeeded': '上传成功',
    'File uploaded successfully': '文件上传成功',
    'Screenshot upload failed': '截图上传失败',
    'Copied to the clipboard': '已拷贝到剪贴板',
    'URL copied to the clipboard': '网址已拷贝到剪贴板',
    'Text copied to the clipboard': '文字已拷贝到剪贴板',
    'Text without line breaks copied': '已拷贝无换行文字',
    'No text detected': '未检测到文字',
    'Something went wrong': '出错了',
    'Downloading New Version': '正在下载新版本',
    'Unable to update Shottr': '无法更新 Shottr',
    'Open in Default App': '在默认应用中打开',
    'Click to open in Finder': '点击在访达中打开',
    'Hit Enter to crop': '按回车键裁剪',
    'Select area first': '请先选择区域',
    'You didn\'t select the area': '你没有选择区域',
    'Take a screenshot first': '请先截图',
    'Copy image first': '请先拷贝图像',
    'Preparing to index': '正在准备索引',
    'Preparing to index your files...': '正在为文件建立索引…',
    'Finishing indexing': '索引即将完成',
    'Screenshot Library is disabled': '截图库已禁用',
    'Click to switch PX/PT': '点击切换 像素/点',
    'Enter': '输入',

    # ===== 错误标题 =====
    'Error': '错误',
    'Problem Occurred': '出现问题',
    'Image Reading Error': '图像读取错误',
    'Image Source Reading Error': '图像源读取错误',
    'Error Resizing Image': '调整图像大小出错',
    'File Writing Error': '文件写入错误',
    'JSON Parsing Error': 'JSON 解析错误',
    'JSON Encoding Error': 'JSON 编码错误',
    # ===== 用户反馈补充 =====
    'Capture Screen': '截取屏幕',
    'Capture Area': '截取区域',
    'Capture Window': '截取窗口',
    'Capture Fullscreen': '截取全屏',
    'Capture Selection': '截取选区',
    'More': '更多',
    'More...': '更多…',
    'More…': '更多…',
    'More Tools': '更多工具',
    'Shottr on Twitter': 'Shottr 官方 Twitter',
    'Shot on Twitter': 'Twitter 官方账号',
    'Follow on Twitter': '关注官方 Twitter',
    'Purchase...': '购买…',
    'Purchase…': '购买…',
    'Purchase': '购买',
    'Buy Shottr': '购买 Shottr',
    'Buy': '购买',
    'Upgrade': '升级',
    'Report a Bug': '报告问题',
    'Report a': '报告',

    # ===== 设置窗口常见标签 =====
    'Screen': '屏幕',
    'Editor': '编辑器',
    'Output': '输出',
    'Integrations': '集成',
    'Misc': '杂项',
    'Hotkeys': '快捷键',
    'Interface': '界面',
    'Recording': '录制',
    'Screen Recording': '屏幕录制',
    'Annotate': '标注',
    'Save to': '保存到',
    'Save To': '保存到',
    'Open screenshots in editor': '在编辑器中打开截图',
    'Play sound': '播放声音',
    'Show mouse cursor': '显示鼠标指针',
    'Image format': '图像格式',
    'Filename template': '文件名模板',
    'Test': '测试',
    'Apply': '应用',
    'Restore': '恢复',
    'Add': '添加',
    'Remove': '移除',
    'Enable': '启用',
    'Disable': '禁用',
    'Restart': '重启',
    'Setup': '设置',
    'Configure': '配置',
    'Account': '账户',
    'Storage': '存储',
    'Server': '服务器',
    'Clipboard': '剪贴板',
    'Recognition': '识别',
    'Updates': '更新',
    'About': '关于',

    # ===== 日志抓取的遗漏项（第二轮）=====
    'Update the app': '更新应用',
    'Reopen Shottr': '重新打开 Shottr',
    'Scrolling (Up)': '滚动截图（向上）',
    'Purchase Shottr': '购买 Shottr',
    'Image size': '图像尺寸',
    'Uploading': '上传',
    'Uploading…': '上传中…',
    '7 days': '7 天',
    '1 day': '1 天',
    '30 days': '30 天',
    'Forever': '永久',
    'Never': '从不',
    'Activate Shottr': '激活 Shottr',
    'Activate': '激活',
    'Crop/Select (V)': '裁剪/选择 (V)',
    'Crop/Select': '裁剪/选择',
    'Did you know that properly purchased apps on average run 18.3% faster?': '你知道吗？正版购买的应用平均运行速度要快 18.3%。',
    'Your tier: Free': '当前版本：免费版',
    'Your tier: Pro': '当前版本：专业版',
    # ===== 第三轮：设置窗口详情 / 二进制预筛 =====
    'When you purchase the app, I get to end my work day 5 minutes earlier. No kidding.': '购买此应用后，我每天就能提前 5 分钟下班。不骗你。',
    'Activate the app': '激活应用',
    'Adding Capture is only available after the license activation.': '添加截图需先激活许可证。',
    'Gradient Backdrop is only available after the license activation.': '渐变背景需先激活许可证。',
    'S3 uploading is only available after the license activation.': 'S3 上传需先激活许可证。',
    'Experimental features are only available to the Friends Club users.': '实验性功能仅向会员用户开放。',
    'Purchase and activate the app to add a pretty background': '购买并激活后才能使用精美背景',
    'Purchase and activate the app to use custom colors': '购买并激活后才能使用自定义颜色',
    'Your license number is saved': '你的许可证编号已保存',
    'License is checked': '许可证已验证',
    'Launch at Startup': '开机时启动',
    'Reset all settings': '重置所有设置',
    'Automatic mode optimizes size and quality based on the image content. If the screenshot has gradients, noise or photographs, it\'ll be saved as Jpeg. If the screenshot contains text and flat colors, it will be saved as PNG.': '自动模式会根据图像内容优化大小与质量：若截图包含渐变、噪点或照片，将保存为 JPEG；若包含文字和纯色，将保存为 PNG。',
    'Choose default folder': '选择默认文件夹',
    'Default folder is not set': '未设置默认文件夹',
    'Pick a folder for your screenshots.': '为你的截图选择一个文件夹。',
    'Enable URL Scheme (Deep Links)': '启用 URL Scheme（深层链接）',
    'Every time you save a screenshot with Shottr, it will appear here.': '每次用 Shottr 保存截图后，都会显示在这里。',
    'Screenshot Library is disabled': '截图库已禁用',
    'Screenshots that you save': '你保存的截图',
    'Click to open in Finder': '点按在访达中打开',
    'Click to switch PX/PT': '点按切换 PX/PT',
    'Capture Active Window': '截取活动窗口',
    'Capture Any Window': '截取任意窗口',
    'Fullscreen Screenshot': '全屏截图',
    'Delayed Screenshot (3s)': '延时截图（3秒）',
    'Scrolling Capture': '滚动截图',
    'Scrolling Capture (Up)': '滚动截图（向上）',
    'Manual Scrolling Capture': '手动滚动截图',
    'Window Capture': '窗口截图',
    'Area Capture': '区域截图',
    'Repeat Area Capture': '重复上次区域截图',
    'Start Scrolling (Up or Down)': '开始滚动（向上或向下）',
    'Scrolling Capture requires accessibility permissions': '滚动截图需要辅助功能权限',
    'Recognize Text/QR': '识别文字/二维码',
    'Text/QR Recognition': '文字/二维码识别',
    'Select rectangle with text that you want to recognize and copy': '框选想要识别并复制的文字区域',
    'Shottr needs permission to record the screen': 'Shottr 需要屏幕录制权限',
    'Shottr needs the screen recording permission to perform OCR': 'Shottr 需要屏幕录制权限才能进行文字识别',
    'Permissions Not Granted': '未授予权限',
    'Checking connection': '正在检查连接',
    'Upload Succeeded': '上传成功',
    'Upload Integration is Off': '上传集成已关闭',
    'Image Upload is Off': '图像上传已关闭',
    'Enable Image Upload in app settings first': '请先在应用设置中启用图像上传',
    'The image uploaded to your custom storage': '图像已上传到你的自定义存储',
    'File uploaded successfully': '文件上传成功',
    'Screenshot upload failed': '截图上传失败',
    'No Image to Upload': '没有可上传的图像',
    'Copied to the clipboard': '已拷贝到剪贴板',
    'Text copied to the clipboard': '文字已拷贝到剪贴板',
    'Text without line breaks copied': '已复制不含换行的文字',
    'Load From Clipboard': '从剪贴板载入',
    'Downloading New Version': '正在下载新版本',
    'Unable to update Shottr': '无法更新 Shottr',
    'Something went wrong': '出错了',
    'Problem Occurred': '出现问题',
    'Open in Default App': '用默认应用打开',
    'Save As': '存储为',
    'Hit Enter to crop': '按回车键裁剪',
    'Take a screenshot first': '请先截图',
    'Take a screenshot before adding a capture to it': '请先截图，再为其添加截图',
    'You can change scrolling height limit in the app preferences': '你可以在应用偏好设置中调整滚动高度限制',
    'No windows are present, try taking a fullscreen screenshot instead': '当前没有可用窗口，请尝试全屏截图',
    'Shottr wasn\'t able to scroll': 'Shottr 无法滚动',
    'Shottr is on Black Friday sale': 'Shottr 黑色星期五优惠中',
    'Manage': '管理',
    'Change': '更改',
    'Accept': '接受',
    'Forget': '忘记',
    'Clear': '清除',
    'Delete': '删除',
    'Custom': '自定义',
    'Auto': '自动',
    'Add Gradient Background': '添加渐变背景',
    'Transparent Background': '透明背景',
    'Arrow (A)': '箭头 (A)',
    'Text (T)': '文字 (T)',
    'Ruler (1 or 2)': '标尺 (1 或 2)',
    'Rectangle (R)': '矩形 (R)',
    'Oval (O)': '椭圆 (O)',
    'Highlighter (H)': '荧光笔 (H)',
    'Spotlight (S)': '聚光灯 (S)',
    'Magnifier (M)': '放大镜 (M)',
    'Counter (C)': '编号 (C)',
    'Backdrop (K)': '背景 (K)',
    'Paste Image (⌘V)': '粘贴图像（⌘V)',
    'Add Capture (⌘A)': '新建截图（⌘A)',
    'Floating Pin (⌘P)': '浮动钉图（⌘P)',
    'Save (⌘S)': '保存（⌘S）',
    'Upload and Get Link (⌘U)': '上传并获取链接（⌘U)',
    'Copy (Esc or ⌘C)': '复制（Esc 或 ⌘C）',
    # ===== 第四轮：设置窗口二级标签（视图树遍历捕获）=====
    # --- 通用 ---
    'Window Screenshot Background': '窗口截图背景',
    'Wallpaper': '壁纸',
    'Transparent': '透明',
    'Solid Color': '纯色',
    'Trim shadow': '裁掉阴影',
    'Title': '标题',
    'Screenshots folder': '截图文件夹',
    'Auto (PNG/JPEG)': '自动（PNG/JPEG）',
    'Save format': '保存格式',
    'Resize retina screenshots': '调整 Retina 截图分辨率',
    'Downscale to 1× when saving': '保存时缩至 1×',
    'Select Folder': '选择文件夹',
    'Scrolling screenshot max height': '滚动截图最大高度',
    'Scrolling screenshot speed': '滚动截图速度',
    'Thumbnail': '缩略图',
    'After Area Crop, show': '区域截图后显示',
    'Autostart': '自动启动',
    'Show': '显示',
    'After screenshot': '截图后',
    'Manually (close button)': '手动（关闭按钮）',
    'Automatically (click outside)': '自动（点击外部）',
    'Hide preview thumbnail': '隐藏预览缩略图',
    # --- 快捷键 ---
    'Reassign Default': '重设默认',
    'Reassign default shortcuts': '重新分配默认快捷键',
    'Steps to assign ⌘⇧4 to Shottr': '将 ⌘⇧4 分配给 Shottr 的步骤',
    '1. Go to System Settings → Keyboard → Keyboard Shortcuts': '1. 打开 系统设置 → 键盘 → 键盘快捷键',
    '2. Select "Screenshots" and uncheck checkboxes for system shortcuts': '2. 选择"截图"，取消勾选系统快捷键',
    'Open System Settings': '打开系统设置',
    '3. Put ⌘⇧3 into Fullscreen and ⌘⇧4 into Area fields below': '3. 将 ⌘⇧3 填入下方"全屏"栏，⌘⇧4 填入"区域"栏',
    'How to reassign default shortcuts': '如何重新分配默认快捷键',
    'Area screenshot': '区域截图',
    'Active window screenshot': '活动窗口截图',
    'Scrolling screenshot': '滚动截图',
    'Instant Text/QR Recognition': '即时文字/二维码识别',
    'Repeat area screenshot': '重复区域截图',
    'Any window screenshot': '任意窗口截图',
    # --- 上传 ---
    'Image Uploading & Link Sharing': '图像上传与链接分享',
    'Disable Uploading': '禁用上传',
    'Shottr Cloud': 'Shottr 云',
    'S3 (Amazon, Cloudflare, Backblaze, etc.)': 'S3（Amazon、Cloudflare、Backblaze 等）',
    'Requires Activation': '需要激活',
    'Access key': 'Access Key',
    'Secret key': 'Secret Key',
    'Bucket': '存储桶',
    'Service': '服务',
    'Amazon (AWS)': 'Amazon（AWS）',
    'Other': '其他',
    'Endpoint': '端点',
    'Key prefix (path)': '键前缀（路径）',
    'Test Connection': '测试连接',
    'Checking': '检查中',
    'Link sharing': '链接分享',
    "Don't Generate URL": '不生成 URL',
    "Don’t Generate URL": '不生成 URL',
    'Generate Presigned URL': '生成预签名 URL',
    'Generate Public Bucket URL': '生成公共存储桶 URL',
    'Link Expiration': '链接有效期',
    'Presigned URLs are only valid for up to 7 days': '预签名 URL 最长有效期为 7 天',
    'Public bucket URL': '公共存储桶 URL',
    'Will only work if your bucket is public': '仅当存储桶为公共访问时有效',
    'Learn More': '了解更多',
    'Get a Token': '获取 Token',
    'To upload images to Shottr Cloud, you need a security token. Think of it as a secret code that grants access to your uploads.': '要上传图像到 Shottr 云，需要一个安全令牌，可将其视为访问你上传内容的密钥。',
    'Shottr allows you to upload an image online and generate a shareable link. Use the dropdown above to enable this functionality.': 'Shottr 支持将图像上传到网络并生成分享链接。使用上方下拉菜单启用此功能。',
    # --- 高级 ---
    'Primary OCR language': 'OCR 主语言',
    'OCR line breaks': 'OCR 换行',
    'Remove line breaks': '移除换行',
    'Menubar icon': '菜单栏图标',
    'Hide menubar icon': '隐藏菜单栏图标',
    'Splash window': '启动闪屏',
    "Don't show splash": '不显示闪屏',
    "Don’t show splash": '不显示闪屏',
    'Main window': '主窗口',
    'Always on top': '始终置顶',
    'Zoom with mouse wheel': '鼠标滚轮缩放',
    'Reverse scroll direction': '反转滚动方向',
    'Default zoom level': '默认缩放级别',
    'Prefer 100%': '优先 100%',
    'Action when hiding with Esc': '按 Esc 隐藏时的操作',
    'Confirmation style': '确认样式',
    'Custom Notification': '自定义通知',
    'System Notification': '系统通知',
    'None': '无',
    'URL Scheme API': 'URL Scheme API',
    'Enable deep links': '启用深层链接',
    'Diagnostics information': '诊断信息',
    'Allow collection': '允许收集',
    # --- 许可证 ---
    'Your license number is in the confirmation email that you receive after purchasing Shottr': '你的许可证编号在购买 Shottr 后收到的确认邮件中',
    'Regular tier. Purchase Shottr and get rid of the Annoying Fellow.': '免费版。购买 Shottr 即可摆脱烦人的小伙伴。',
    'Purchase License': '购买许可证',
    'Thank you for purchasing': '感谢购买',
    'Explore hidden features': '探索隐藏功能',
    'Restore License': '恢复许可证',
    'I actually own a little dinosaur, I pet him every time the app gets purchased. He loves that.': '我真的养了一只小恐龙，每当有人购买这个应用我就摸摸它，它可喜欢了。',
    # --- 欢迎/其他弹窗 ---
    'Run at Startup': '开机时启动',
    'Setup Hotkeys': '设置快捷键',
    'Update Shottr': '更新 Shottr',
    'Next Time': '下次再说',
    'Maybe Later': '以后再说',
    'Hi! I’m the world’s most annoying salesperson. Do you want to buy Shottr?': '嗨！我是世界上最烦人的销售。你想购买 Shottr 吗？',
    "Hi! I'm the world's most annoying salesperson. Do you want to buy Shottr?": '嗨！我是世界上最烦人的销售。你想购买 Shottr 吗？',
    'Later': '稍后',
    'Reset': '重置',
    'Info': '信息',
    # --- 编辑器 ---
    'Shadow': '阴影',
    'Inset': '内嵌',
    'Recenter': '重新居中',
    'Outer Radius': '外半径',
    'Inner Radius': '内半径',
    'Solid': '纯色',
    'Colormix': '混色',
    'Mesh gradient': '网格渐变',
    'Vertical gradient': '垂直渐变',
    'Diagonal gradient': '对角渐变',
    'Radial gradient': '径向渐变',
    'Button': '按钮',
    'Image Blur': '图像模糊',
    'Blur Text': '模糊文字',
    'Erase Text': '擦除文字',
    'Copy Pixel Color': '拷贝像素颜色',
    'Hover mouse over any pixel and press Tab': '将鼠标悬停在任意像素上并按 Tab 键',
    'Copy Text Color': '拷贝文字颜色',
    'Press Shift+Tab to copy the darkest color in the 20px area around the cursor': '按 Shift+Tab 拷贝光标周围 20px 区域内最深的颜色',
    'Copy Average Color': '拷贝平均颜色',
    'Select an area and press C to copy its average color': '框选区域并按 C 键拷贝其平均颜色',
    'Color Format': '颜色格式',
    'One logical point is equal two physical pixels on Retina displays. Use shortcut P to switch modes.': '在 Retina 显示器上，一个逻辑点等于两个物理像素。使用快捷键 P 切换模式。',
    'Resize': '调整大小',
    'Show Size in Logical Points': '以逻辑点显示尺寸',
    'Resize Image': '调整图像大小',
    'Use the keyboard': '使用键盘',
    'Hold a ⓵ or ⓶ key, or an arrow key, and move your mouse over the area which you want to measure': '按住 ⓵ 或 ⓶ 键（或方向键），将鼠标移到要测量的区域上',
    'Got  it!': '明白了！',
    'Label': '标签',
    "Drag'n'Drop Image": '拖放图像',
    'Floating Pin': '浮动钉图',
    'Window': '窗口',
    'Multilingual': '多语言',
    # --- 界面语言列表（原语言名）---
    'Dansk': '丹麦语',
    'Deutsch': '德语',
    'U.S. English': '英语（美国）',
    'Australian English': '英语（澳大利亚）',
    'Canadian English': '英语（加拿大）',
    'British English': '英语（英国）',
    'Indian English': '英语（印度）',
    'Japanese English': '英语（日本）',
    'New Zealand English': '英语（新西兰）',
    'Singapore English': '英语（新加坡）',
    'South African English': '英语（南非）',
    'Español': '西班牙语',
    'Suomi': '芬兰语',
    'Français': '法语',
    'Gaeilge': '爱尔兰语',
    'Magyar': '匈牙利语',
    'Indonesia': '印尼语',
    'Italiano': '意大利语',
    'Lietuvių': '立陶宛语',
    'Norsk bokmål': '挪威语（博克马尔）',
    'Nederlands': '荷兰语',
    'Norsk nynorsk': '挪威语（尼诺斯克）',
    'Polski': '波兰语',
    'Português do Brasil': '葡萄牙语（巴西）',
    'Português Europeu': '葡萄牙语（欧洲）',
    'Română': '罗马尼亚语',
    'Slovenščina': '斯洛文尼亚语',
    'Svenska': '瑞典语',
    # OCR 识别语言列表
    'English+': '英文（增强）',
    'French': '法语',
    'Italian': '意大利语',
    'German': '德语',
    'Spanish': '西班牙语',
    'Portuguese (Brazil)': '葡萄牙语（巴西）',
    'Chinese': '中文',
    'Chinese (Cantonese)': '中文（粤语）',
    'Korean': '韩语',
    'Japanese': '日语',
    'Cyrillic': '西里尔文',
    'Ukrainian': '乌克兰语',
    'Thai': '泰语',
    'Vietnamese': '越南语',
    'Arabic': '阿拉伯语',
    'Arabic (Najdi)': '阿拉伯语（纳季迪）',
    'Turkish': '土耳其语',
    'Indonesian': '印尼语',
    'Czech': '捷克语',
    'Danish': '丹麦语',
    'Dutch': '荷兰语',
    'Norwegian': '挪威语',
    'Norwegian (Nynorsk)': '挪威语（尼诺斯克）',
    'Norwegian (Bokmål)': '挪威语（博克马尔）',
    'Malay': '马来语',
    'Polish': '波兰语',
    'Romanian': '罗马尼亚语',
    'Swedish': '瑞典语',
}

PREFIX = {
    # 带变量的标题（Swift 字符串插值）
    'Paste Image (': '粘贴图像（',
    'Save (': '保存（',
    'Upload and Get Link (': '上传并获取链接（',
    'Add Capture (': '新建截图（',
    'Floating Pin (': '浮动钉图（',
    'Copy (Esc or ': '复制（Esc 或 ',
    'Copy as ': '拷贝为 ',
    'Go to System Settings ': '前往系统设置 ',
    'Files (': '文件（',
    'Upload f': '上传失败',
    'Test Fai': '测试失败',
}

def main():
    data = {'exact': EXACT, 'prefix': PREFIX}
    # 输出到仓库内 dict/ 目录，由 install.sh 部署到应用 Resources
    import os
    out = os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'dict', 'zh_dict.plist'))
    with open(out, 'wb') as f:
        plistlib.dump(data, f)
    print(f'written {out}: exact={len(EXACT)} prefix={len(PREFIX)}')

if __name__ == '__main__':
    main()
